name: "CI"

on:
  pull_request:
  push:

permissions:
  contents: read

jobs:
  tests:
    name: "Test on PHP ${{ matrix.php-version }}"

    runs-on: 'ubuntu-latest'

    continue-on-error: true

    strategy:
      matrix:
        php-version:
          - '7.3'
          - '7.4'
          - '8.0'
          - '8.1'
          - '8.2'

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v2

      - name: "Install PHP with extensions"
        uses: shivammathur/setup-php@v2
        with:
          coverage: "none"
          php-version: ${{ matrix.php-version }}
          ini-values: memory_limit=-1

      - name: "Add PHPUnit matcher"
        run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - run: composer install

      - name: "Run tests"
        run: vendor/bin/phpunit
